# Generated by Django 2.1.7 on 2019-04-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiarmParam',
            fields=[
                ('apID', models.AutoField(primary_key=True, serialize=False)),
                ('aContent', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('aState', models.CharField(max_length=10, null=True)),
                ('exDay', models.IntegerField(null=True)),
                ('aKind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.AiarmParam')),
            ],
        ),
        migrations.CreateModel(
            name='BidInvitation',
            fields=[
                ('inviteID', models.AutoField(primary_key=True, serialize=False)),
                ('inviteTime', models.DateField(null=True)),
                ('inviteName', models.CharField(max_length=30, null=True)),
                ('inviteContent', models.TextField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('resWay', models.CharField(max_length=200, null=True)),
                ('preBidTime', models.DateField(null=True)),
                ('response', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidRequest',
            fields=[
                ('rID', models.AutoField(primary_key=True, serialize=False)),
                ('rKind', models.CharField(max_length=2, null=True)),
                ('rName', models.CharField(max_length=30, null=True)),
                ('rContent', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('isWin', models.BooleanField(null=True)),
                ('winPrice', models.IntegerField(null=True)),
                ('winCompany', models.CharField(max_length=30, null=True)),
                ('lostReason', models.CharField(max_length=30, null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractID', models.AutoField(primary_key=True, serialize=False)),
                ('newVerID', models.IntegerField(null=True)),
                ('contractDocPath', models.TextField(null=True)),
                ('contractPrice', models.IntegerField(null=True)),
                ('firPartPrice', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('secPartPrice', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('thrPartPrice', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('firTimeSpan', models.IntegerField(null=True)),
                ('secTimeSpan', models.IntegerField(null=True)),
                ('thrTimeSpan', models.IntegerField(null=True)),
                ('productTime', models.IntegerField(null=True)),
                ('conveyTime', models.IntegerField(null=True)),
                ('FATDoc', models.TextField(null=True)),
                ('SATDoc', models.TextField(null=True)),
                ('signTime', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False)),
                ('cName', models.CharField(max_length=50, null=True)),
                ('cEnglishName', models.CharField(max_length=100, null=True)),
                ('cAddress', models.CharField(max_length=80, null=True)),
                ('cContactPerson', models.CharField(max_length=20, null=True)),
                ('cPhone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=20, null=True)),
                ('deviceID', models.CharField(max_length=200, null=True)),
                ('functionWord', models.CharField(max_length=100, null=True)),
                ('picPath', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('requestContent', models.TextField(null=True)),
                ('answer', models.CharField(max_length=2, null=True)),
                ('remark', models.TextField(null=True)),
                ('contractID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=40, null=True)),
                ('startTime', models.DateField(null=True)),
                ('endTime', models.DateField(null=True)),
                ('bidPrice', models.IntegerField(null=True)),
                ('bidDocPath', models.TextField(null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('isGuaratee', models.CharField(max_length=2, null=True)),
                ('currentKind', models.CharField(max_length=3, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('aimDevice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Device')),
                ('inviteID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.BidInvitation')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=2, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StateParam',
            fields=[
                ('paramID', models.AutoField(primary_key=True, serialize=False)),
                ('paramContent', models.CharField(max_length=100, null=True)),
                ('remark', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.CharField(max_length=7, null=True)),
                ('uName', models.CharField(max_length=10, null=True)),
                ('uAge', models.IntegerField(null=True)),
                ('uGender', models.CharField(max_length=2, null=True)),
                ('uKind', models.CharField(max_length=2, null=True)),
                ('uPassword', models.CharField(max_length=10, null=True)),
                ('uPhone', models.CharField(max_length=20, null=True)),
                ('uWorkTime', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verID', models.IntegerField(null=True)),
                ('docPath', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('contractID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Contract')),
            ],
        ),
        migrations.AddField(
            model_name='staff_project',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.User'),
        ),
        migrations.AddField(
            model_name='projectproccess',
            name='proccess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.StateParam'),
        ),
        migrations.AddField(
            model_name='project',
            name='pState',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.StateParam'),
        ),
        migrations.AddField(
            model_name='contract',
            name='pID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.StateParam'),
        ),
        migrations.AddField(
            model_name='bidresult',
            name='pID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project'),
        ),
        migrations.AddField(
            model_name='bidrequest',
            name='pID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project'),
        ),
        migrations.AddField(
            model_name='bidinvitation',
            name='cID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Customer'),
        ),
    ]
