# Generated by Django 2.1.7 on 2019-05-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidHelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiarmparam',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='alarm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bidinvitation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bidrequest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bidresult',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='extrarequest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='projectproccess',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='staff_project',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stateparam',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='versionrecord',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='bidinvitation',
            name='response',
        ),
        migrations.AddField(
            model_name='alarm',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bidinvitation',
            name='bidResponse',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='aiarmparam',
            name='aContent',
            field=models.CharField(blank=True, default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarm',
            name='aKind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.AiarmParam'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='aState',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='exDay',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bidinvitation',
            name='endTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidinvitation',
            name='inviteContent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidinvitation',
            name='inviteName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bidinvitation',
            name='inviteTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidinvitation',
            name='preBidTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidinvitation',
            name='resWay',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bidrequest',
            name='rContent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidrequest',
            name='rKind',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='bidrequest',
            name='rName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='isWin',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='lostReason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='winCompany',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='bidresult',
            name='winPrice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='FATDoc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='SATDoc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractDocPath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractPrice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='conveyTime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='firPartPrice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='firTimeSpan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='newVerID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='productTime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='secPartPrice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='secTimeSpan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.StateParam'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='thrPartPrice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='thrTimeSpan',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cAddress',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cContactPerson',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cEnglishName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cPhone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='functionWord',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='picPath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extrarequest',
            name='answer',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='extrarequest',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Contract'),
        ),
        migrations.AlterField(
            model_name='extrarequest',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extrarequest',
            name='requestContent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extrarequest',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aimDevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Device'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bidDocPath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bidPrice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='currentKind',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='endTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='inviteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.BidInvitation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='isGuaratee',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='pName',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='pState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.StateParam'),
        ),
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='startTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproccess',
            name='pID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Project'),
        ),
        migrations.AlterField(
            model_name='projectproccess',
            name='proccess',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bidHelp.StateParam'),
        ),
        migrations.AlterField(
            model_name='projectproccess',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff_project',
            name='job',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='stateparam',
            name='paramContent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stateparam',
            name='remark',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='uAge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uGender',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='uID',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='uKind',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='uName',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='uPassword',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='uPhone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='uWorkTime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='versionrecord',
            name='contractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidHelp.Contract'),
        ),
        migrations.AlterField(
            model_name='versionrecord',
            name='docPath',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='versionrecord',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='versionrecord',
            name='verID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterModelTable(
            name='aiarmparam',
            table='bidhelp_aiarmparam',
        ),
        migrations.AlterModelTable(
            name='alarm',
            table='bidhelp_alarm',
        ),
        migrations.AlterModelTable(
            name='bidinvitation',
            table='bidhelp_bidinvitation',
        ),
        migrations.AlterModelTable(
            name='bidrequest',
            table='bidhelp_bidrequest',
        ),
        migrations.AlterModelTable(
            name='bidresult',
            table='bidhelp_bidresult',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='bidhelp_contract',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='bidhelp_customer',
        ),
        migrations.AlterModelTable(
            name='device',
            table='bidhelp_device',
        ),
        migrations.AlterModelTable(
            name='extrarequest',
            table='bidhelp_extrarequest',
        ),
        migrations.AlterModelTable(
            name='project',
            table='bidhelp_project',
        ),
        migrations.AlterModelTable(
            name='projectproccess',
            table='bidhelp_projectproccess',
        ),
        migrations.AlterModelTable(
            name='staff_project',
            table='bidhelp_staff_project',
        ),
        migrations.AlterModelTable(
            name='stateparam',
            table='bidhelp_stateparam',
        ),
        migrations.AlterModelTable(
            name='versionrecord',
            table='bidhelp_versionrecord',
        ),
    ]
